

server:
    port: 8080
spring:
    #creiar db na fatec antes de rodar
    datasource:
        url: jdbc:mysql://localhost:3306/testdb
        username:
        password:
        driver-class-name:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: 
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
cors:
    origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000, http://localhost:8000}
#A linha abaixo ativa debug no prompt
logging:
    level:
        org:
            springframework:
                security: DEBUG