

server:
  port: 8080
spring:
  #criar db na fatec antes de rodar
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  origins: ${CORS_ORIGINS}
#A linha abaixo ativa debug no prompt
logging:
  level:
    org:
      springframework:
        security: DEBUG
api:
  security:
    token:
      #NÃO COMMITAR COM A LINHA ABAIXO PREENCHIDA
      secret: ${JWT_SECRET}