server:
  port: 8080
spring:
  #criar db na fatec antes de rodar
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bookshifter}
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL:book.shifter.brazil@gmail.com}
    password:  ${SMTP_PASSWORD:mvsqdhfcbdnj knqn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  origins: ${CORS_ORIGINS:http://localhost:5000}
#A linha abaixo ativa debug no prompt
logging:
  level:
    org:
      springframework:
        security: DEBUG
api:
  security:
    token:
      #NÃO COMMITAR COM A LINHA ABAIXO PREENCHIDA
      secret: ${JWT_SECRET:5T#45NA^r2s=}